title: "Bedfest 2023"
remote_theme: pmarsceill/just-the-docs
color_scheme: "bedlam"
search_enabled: true
aux_links:
  "Bedfest 2023 Page": 
    - "https://www.bedlamtheatre.co.uk/seasons/bedfest2023"
aux_links_new_tab: true
